# Generated by Django 5.1 on 2026-01-12 09:57

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_first_name', models.CharField(max_length=20, validators=[company.models.validate_name])),
                ('primary_contact_last_name', models.CharField(max_length=20, validators=[company.models.validate_name])),
                ('company_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
