# Generated by Django 5.1 on 2026-03-14 04:25

import company.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_newentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['company_name']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='company.company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[company.models.validate_gst]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('company', 'gst_number')},
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company'], name='company_ven_company_eaa361_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['gst_number'], name='company_ven_gst_num_4743d9_idx'),
        ),
    ]
