# Generated by Django 5.1 on 2026-01-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_name_vendor_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
