# Generated by Django 5.1 on 2026-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_company',
            field=models.CharField(blank=True, help_text='Manufacturer/Brand name', max_length=100, null=True),
        ),
    ]
