# Generated by Django 5.1 on 2026-01-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productbatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='purchase_order',
            new_name='order',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='batch_number',
            field=models.CharField(default='OLD-BATCH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiry_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
    ]
