# Generated by Django 5.1 on 2026-01-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name_transaction'),
        ('inventory', '0013_rename_purchase_order_purchaseorderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
