# Generated by Django 5.1 on 2026-01-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_purchaseorderitem_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
