# Generated by Django 5.1 on 2026-01-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_purchaseorderitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('other', 'Other')], on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='inventory.customer'),
        ),
    ]
