# Generated by Django 5.1 on 2026-01-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='customer',
            field=models.ForeignKey(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('other', 'Other')], on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='inventory.customer'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=10),
        ),
    ]
