# Generated by Django 5.1 on 2026-01-16 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_customer_gst_number_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch used for this transaction (FEFO tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
