# Generated by Django 5.1 on 2026-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_stocktransaction_batch_alter_customer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
