# Generated by Django 5.1 on 2026-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_address_created_at_address_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
