# Generated by Django 5.2.6 on 2026-03-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_purchaseorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abc_class',
            field=models.CharField(blank=True, choices=[('A', 'A - High Value'), ('B', 'B - Medium Value'), ('C', 'C - Low Value')], max_length=1, null=True),
        ),
    ]
