# Generated by Django 5.1 on 2026-03-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_product_abc_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
